development:
  adapter: postgresql
  encoding: unicode
  database: rails_books_development
  host: localhost
  pool: 5
  username: "postgres"
  password: "postgres"

production:
  adapter: postgresql
  encoding: unicode
  database: rails_books_production
  host: localhost
  pool: 5
  username: "postgres"
  password: "postgres"

test:
  adapter: postgresql
  encoding: unicode
  database: rails_books_test
  host: localhost
  pool: 5
  username: "postgres"
  password: "postgres"
